### PR TITLE
add logo and facivon to App

### PR DESCRIPTION
**Pull request by Quetourah**
- add the favicon for the browser tab
- add the app's logo to app

### CODE REVIEW

**Comment by Quetourah** [comment]
image
this is what the favicon looked like in my chrom browser

**Comment by jhrbva** [comment]
I think we should remove "Let's get there together" from the logo itself and just add it as a tag line to the front-page of the site, otherwise it might look a little busy when we use it in other locations on the site like on a header or navigation bar. Also I think that we should make the size of the location pins and of the word Caravan the same, so it looks like we are traveling from C to N, kind of like this: 
Screen Shot 2020-03-06 at 10 58 04 AM
What do you think of this idea?

**Comment by kcode20** [comment]
I love that idea @jhrbva!!

**Comment by Quetourah** [comment]
sure @jhrbva. Not sure if I'll do it today, but I can definitely finish it next sprint.

**Comment by kcode20** [comment]
This ticket relates to: https://caravanning.atlassian.net/browse/CA-54

**Comment by Quetourah** [comment]
Screen Shot 2020-03-08 at 4 42 13 PM
How does this look @jhrbva ? I can't seem to find a line similar to the one you show in your example. If this line isn't the best, I can share the canva file with you and you can edit it.

**Comment by jhrbva** [comment]
@Quetourah I think this looks a lot cleaner already but I'd love to play with it a bit more. I know you are busy with other scrum master related work so if you send me the file I'd be happy to work on it.
If you want to push the favicon and close this PR I can open another one for the logo later on.

**Pull request merged**
