### PR TITLE
Create Trip (CA-104)

### PR DESCRIPTION
**Pull request by kcode20**
#### Related Issues
https://caravanning.atlassian.net/browse/CA-104

#### Description
On submit of the trip form, we should create a new trip. 

###### DoD: 
- has a “create new trip” button
- on submit call POST /trips
- reroute to the user dashboard after submission. 

#### Comments
This ticket also updates all forms to be using `react-bootstrap`.

#### Testing
Add a step-by-step list on how to test this PR, like this:
- [ ] Run the React Client Application by running `yarn start` (or `npm start`)
- [ ] Direct to `localhost:3000/dashboard` in your browser.
- [ ] Click the Create a New Trip Button
- [ ] Once on the Trip form, fill out the information and submit the trip. 

**Note:** you will need to submit the date in `MM-DD-YY` format and the time in `HH:MM:SS` format for this to work. Check the gif below to reference the testing flow:
SubmitTrip

## How are you feeling?
👍

### CODE REVIEW

**Comment by kcode20** [comment]
Please do not review for now, this ticket is currently a `wip`.

**Comment by kcode20** [comment]
I will add the calls to `reststop` and `members` to a subsequent ticket.

**Comment by Quetourah** [comment]
@kcode20 , I get this error trying to test the PR. The POST request fails on my end. Not sure why.

Screen Shot 2020-03-30 at 11 08 14 AM

**Comment by kcode20** [comment]
Do you have the server running because it works for me.

**Comment by Quetourah** [comment]
> Do you have the server running because it works for me.

I did. I don't know why it's not working for me. I will try again re-running my server but I'd be great if someone else can review it so you can keep working. @connie-code, can you be the second review please?

**Comment by jhrbva** [comment]
I just reviewed this and test were not failing, now they are?! 😕

**Pull request merged**
