### PR TITLE
UI styling the directional box

### PR DESCRIPTION
**Pull request by chanie01234**
## Description
Design the direction box on the google maps interface

## Related Issues
Link any related issues, like this:
https://caravanning.atlassian.net/browse/CA-152

## Testing
Add a step-by-step list on how to test this PR, like this:
- [ ] Run the server by entering `node server.js`
- [ ] Open another terminal tab and enter `yarn start` or `nom start`
- [ ] Go to localhost:3000/map preferably on Google Chrome

## How are you feeling?
Finish your PR with the emoji that best illustrates your spirits at this moment
😺

### CODE REVIEW

**Comment by kcode20** [comment]
Please add a screenshot of how you style it and how we can test this PR.

**Comment by chanie01234** [comment]
Screen Shot 2020-05-08 at 6 43 26 AM

**Comment by chanie01234** [comment]
What's up with this conflict? 
Screen Shot 2020-05-08 at 7 02 47 AM

**Comment by jhrbva** [comment]
> What's up with this conflict?
> Screen Shot 2020-05-08 at 7 02 47 AM

The Instructional Overlay component has since been made a stateful component to accommodate the dynamic instructions display. You need to match your branch to master

**Pull request merged**
