### PR TITLE
CA-97_DELETE_Rest_Stop_Endpoint

### PR DESCRIPTION
**Pull request by Quetourah**
## Related Issues
https://caravanning.atlassian.net/browse/CA-97

## Description
Delete a rest stop from a trip

## Note ⚠️ 
I updated the rest stop table to delete a rest stop based on a unique rest stop id.

## Testing
Test this PR:
- [ ] Run the server with `node server.js`
- [ ] Go to Postman and to do a DELETE request using `localhost:8080/reststop`
- [ ] Go to the body tab and add the `reststopid` as indicated in the image below

>  **_One review can use 7 and the other 4. Leave the number you used in a comment._**

Screen Shot 2020-04-02 at 5 06 17 PM

You will get `Ok` as a response if the request is successful.

## How are you feeling?
💯

### CODE REVIEW

**Comment by kcode20** [comment]
I agree with your note, we should add an `id` column for the `reststops`. When someone wants to delete a particular rest stop we can select it by it's `id`

**Comment by Quetourah** [comment]
> I agree with your note, we should add an `id` column for the `reststops`. When someone wants to delete a particular rest stop we can select it by it's `id`

should I create a new ticket for it or just do it as part of this ticket? @kcode20

**Comment by kcode20** [comment]
I think you should create a new ticket

**Comment by Quetourah** [comment]
Alright. I will add the ticket and complete it.

**Pull request merged**
